### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by shadowhen** [AlekseyAfonin/EquipBestItem#3]
Hi Aleksey,

Can you add a license to your repository? I suggest MIT license, but you can use any other license if you want to. If you need to know your options, you can check this [choosealicense.com](https://choosealicense.com/).

Other Bannerlord mods [Bannerlord Tweaks](https://github.com/mipen/BannerlordTweaks), [Bannerlord Community Patch](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch), and [Bear My Banner](https://github.com/SebLavK/BearMyBanner) utilize licenses for a good reason.

If you have any questions about licensing, I try my best to answer them. Just to be clear, I am not lawyer, but I want to help you to improve the project.

**Comment by s0x7C5** [comment]
Hi Henry,
Thank you for the corrections. I added a license. I've finished refactoring. There are still a couple of places that I will change later, but there will probably be no big changes.
