### ISSUE TITLE
1.4.3 Beta Compatibility?

### ISSUE THREAD

**Issue by shadowhen** [AlekseyAfonin/EquipBestItem#6]
TaleWorlds has released a 1.4.3 beta patch, and when I look at the mod's posts on NexusMods, people talk about a crashing issue. I found one issue with the code, which the  **_MyInventoryLogic_** does not exist.
```csharp
public MainViewModel()
{
    _inventoryLogic = InventoryManager.MyInventoryLogic;
    _inventory = InventoryBehavior.Inventory;
}
```
I replace **_MyInventoryLogic_** with **_InventoryLogic_,** which result the mod to build successfully and work properly for now.
```csharp
public MainViewModel()
{
    _inventoryLogic = InventoryManager.InventoryLogic;
    _inventory = InventoryBehavior.Inventory;
}
```
I haven't checked if the code would work on the stable patch 1.4.2., but TaleWorlds has refactored and cleaned up its code according to patch notes for beta.

**Comment by shadowhen** [comment]
I also fixed the mod by uploading one to [NexusMod](https://www.nexusmods.com/mountandblade2bannerlord/mods/1996). I can remove or hide it if you want me to. Here is the [changed file](https://github.com/shadowhen89/EquipBestItem/commit/4448a5ffbd105fb5555dd634a521c2990e0590a4) in question for fixing.

**Comment by s0x7C5** [comment]
Hello, Henry. Thanks for the fix. I don't have time to do the mod yet, so let it be up to you.
